recipe: default.v1

language: "is"
 
pipeline:
 - name: WhitespaceTokenizer
 - name: LexicalSyntacticFeaturizer
 - name: RegexFeaturizer
 - name: CountVectorsFeaturizer
   analyzer: char_wb
   min_ngram: 1
   max_ngram: 4
 - name: LanguageModelFeaturizer
#   model_name: "convbert"
#   model_weights: "jonfd/convbert-base-igc-is"
   model_name: "bert"
   model_weights: "grammatek/icelandic-ner-bert"
 - name: DIETClassifier
   epochs: 100
 - name: FallbackClassifier
   threshold: 0.7
 - name: EntitySynonymMapper
 - name: classifiers.bin_entity_extractor.BinEntityExtractor
   match_training_data: true
   match_all_entities: false
   entity_mappings:
     contact:
       - ism
       - gæl
       - föð
       - móð
       - erm
 - name: ResponseSelector
   epochs: 100
   retrieval_intent: faq
 - name: ResponseSelector
   epochs: 100
   retrieval_intent: chitchat
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
