recipe: default.v1

language: "is"
 
pipeline:
 - name: WhitespaceTokenizer
 - name: LexicalSyntacticFeaturizer
 - name: RegexFeaturizer
 - name: CountVectorsFeaturizer
   additional_vocabulary_size:
     text: 1000
   analyzer: word
   OOV_token: oov
   token_pattern: (?u)\b\w+\b
   use_shared_vocab: true
 - name: CountVectorsFeaturizer
   analyzer: char_wb
   min_ngram: 1
   max_ngram: 4
 - name: LanguageModelFeaturizer
   model_name: "bert"
   model_weights: "grammatek/icelandic-ner-bert"
   #model_weights: "sentence-transformers/LaBSE"
 - name: DIETClassifier
   epochs: 100
   constrain_similarities: true
   BILOU_flag: true
 - name: EntitySynonymMapper
 - name: FallbackClassifier
   threshold: 0.7
 - name: ResponseSelector
   epochs: 100
   retrieval_intent: faq
 - name: ResponseSelector
   epochs: 100
   retrieval_intent: chitchat
policies:
 - name: MemoizationPolicy
 - name: RulePolicy
      # Confidence threshold for the `core_fallback_action_name` to apply.
      # The action will apply if no other action was predicted with
      # a confidence >= core_fallback_threshold. Note: core-threshold != nlu-threshold
   core_fallback_threshold: 0.4
   core_fallback_action_name: "action_default_fallback"
   enable_fallback_prediction: true
 - name: UnexpecTEDIntentPolicy
   tolerance: 0.5
   max_history: 5
   epochs: 100
   constrain_similarities: true
 - name: TEDPolicy
   max_history: 5
   epochs: 100
   constrain_similarities: true

