name: Train and test Rasa

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
env:
  RASA_VERSION: 3.4.2
  FUSEKI_VERSION: 4.7.0
  FUSEKI_NETWORK_HOST: localhost
  FUSEKI_NETWORK_PORT: 3030
  DEBUG_MODE: true

jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Start containers
        run: |
          docker-compose -f "docker-compose.yml" build
          docker-compose -f "docker-compose.yml" -f "fuseki_override_template.yml" up -d fuseki
      - name: Run PyTest
        run: |
          docker ps
          echo "FUSEKI_NETWORK_HOST:FUSEKI_NETWORK_PORT: $FUSEKI_NETWORK_HOST:$FUSEKI_NETWORK_PORT"
          source venv/bin/activate
          export PYTHONPATH="`pwd`/src/municipal_info_api"
          pytest -v --junitxml=report.xml .
      - name: Publish PyTest Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'report.xml'
      - name: Rasa Train and Test
        # Use our own fork of the seemingly unmaintained RasaHQ gha
        uses: SDiFI/rasa-train-test-gha@sdifi
        with:
          rasa_version: '3.4.2'
          data_validate: true # Validates domain and data files to check for possible mistakes
          rasa_train: true # Run rasa train
          rasa_test: true # Run rasa test
          test_args: --fail-on-predicion-errors # Fail pipeline when test fails
          test_type: all # Run both 'core' and 'nlu' tests
          # In order to add a PR comment with summary
          # a GH Token has to be pass to the GH action
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop containers
        run: docker-compose -f "docker-compose.yml" down
      - name: Upload model
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models
      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results and model
          path: |
            models
            results
            reports
